# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнила:
- Плясунова Милена Юрьевна
- ПИЭ-21-2

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

Работу проверил:
- к.э.н., доцент Панов М.А.

# Лабораторные работы
## Лабораторная работа №1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи.
### P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания

```python
from functools import lru_cache

@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

if __name__ == '__main__':
    print(fibonacci(100))
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/L101.png)

## Лабораторная работа №2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.
### Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента.

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func

@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138, 15, 48, 2)
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/L102.png)

## Лабораторная работа №3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string.
### Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт.
### Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.

```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/L103.png)

## Лабораторная работа №4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводится “Успешная регистрация”.

```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина больше 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '12345678910'
    check_name(name)
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/L104.png)

## Лабораторная работа №5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')

@SiteChecker
def site():
    print('Усердная работа сайта')

if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/L105.png)

# Самостоятельные работы
## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.
### Подсказка: необходимо использовать модуль time.
### Декоратор необходимо использовать для этой функции:

```python
def fibonacci():
 fib1 = fib2 = 1

 for i in range(2, 200):
 fib1, fib2 = fib2, fib1 + fib2
 print(fib2, end=' ')

if __name__ == '__main__':
 fibonacci()
```
### Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы.
### Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды.

```python
import time

def time_counter(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"\nВремя выполнения функции: {elapsed_time} секунд")
        return result
    return wrapper

@time_counter
def fibonacci():
    fib1 = fib2 = 1

    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/S101.png)

## Выводы

1. Декоратор time_counter измеряет время выполнения функции и выводит результат в консоль (он использует модуль time для записи моментов начала и завершения выполнения функции). Затем этот декоратор применяется к функции fibonacci, используя фразу @time_counter. 
2. Функция wrapper служит для замены оригинальной функции при использовании декоратора. Её цель - обернуть вызов оригинальной функции так, чтобы можно было добавить дополнительные функции до и после её выполнения. В ней фиксируется время начала и окончания работы функции fibonacci, при этом оригинальная функция вызывается с теми же аргументами, которые были переданы в декорированную функцию.

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(file_name):
    try:
        with open(file_name, 'r') as file:
            data = file.read()

            if not data:
                raise Exception("Файл пустой")
            else:
                print(data)

    except Exception as e:
        print(e)

read_file('empty.txt')
read_file('full_of_information.txt')
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/S1021.png)
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/S1022.png)

## Выводы

1. Код включает блок try-except, чтобы обрабатывать исключения. Если возникает ошибка при чтении файла (если файл пустой), программа выведет сообщение об ошибке.
2. После чтения файла выполняется проверка на пустоту с помощью "if not data". Эту конструкцию можно разложить до выражения "if bool(data) == False", а наличие следующих значений ('', 0, 0.0, False, None, [], (), {}) эквивалентно False.

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def sum_num():
    try:
        number = input("Введите число: ")
        result = 2 + float(number)
        print(f"Результат сложения: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

sum_num()
sum_num()
sum_num()
sum_num()
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/S103.png)

## Выводы

Сообщения ошибки ValueError возникают, когда передается какой-то параметр функции, функция при этом ожидает один тип данных, а на самом деле передается другой. 

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
def decorator_uppercase(function):
    def wrapper():
        func = function()
        make_uppercase = func.upper()
        return make_uppercase
    return wrapper

@decorator_uppercase
def quote1():
    return 'Teamwork makes the dream work'

@decorator_uppercase
def quote2():
    return 'Work smarter, not harder'

if __name__ == '__main__':
    print(quote1())
    print(quote2())
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/S104.png)

## Выводы
```python
def decorator_uppercase(function):
"""
Функция декоратора, которая принимает другую функцию в качестве аргумента
"""
    def wrapper():
"""
Функция, которая будет 'обёрткой' для оригинальной функции.
"""
        func = function() # оригинальная функция вызывается, и её результат сохраняется в переменной func
        make_uppercase = func.upper() # результат func преобразуется в верхний регистр и сохраняется в переменной make_uppercase
        return make_uppercase
    return wrapper

@decorator_uppercase # применение декоратора к первой функции
def quote1():
    return 'Teamwork makes the dream work'

@decorator_uppercase # применение декоратора ко второй функции
def quote2():
    return 'Work smarter, not harder'

if __name__ == '__main__': # вывод результатов
    print(quote1())
    print(quote2())
```

Декоратор decorator_uppercase принимает функцию, вызывает ее и преобразует текст в верхний регистр с помощью метода upper(). При использовании этого декоратора для функций quote1 и quote2, они возвращают строку в верхнем регистре. Этот пример демонстрирует, насколько удобно использовать декораторы для добавления определенной функциональности к различным функциям без непосредственного изменения их кода.

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class NoDogsAllowedException(Exception):
    pass

def checking(*items):
    forbidden_word = 'собака'

    for item in items:
        if forbidden_word in item.lower():
            raise NoDogsAllowedException('Никаких собак!')

    print('Можете проходить..')

if __name__ == '__main__':
    group1 = ('Кот', 'Черепаха', 'Попугай')
    group2 = ('Собака в шляпе', 'Кот', 'Мышь')

    try:
        checking(*group1)
    except NoDogsAllowedException as e:
        print(e)

    try:
        checking(*group2)
    except NoDogsAllowedException as e:
        print(e)
```

### Результат.
![Меню](https://github.com/Alphaverb/Software_Engineering/blob/Tema_10/pic/S105.png)

## Выводы
```python
class NoDogsAllowedException(Exception):
"""
Здесь определяется новый класс исключения NoDogsAllowedException, который наследуется от встроенного класса Exception.
"""
    pass

def checking(*items):
"""
Определена функция checking, которая принимает произвольное количество аргументов (*items).
"""
    forbidden_word = 'собака' # запрещенное слово

    for item in items: # для каждого элемента в списке
        if forbidden_word in item.lower(): # если есть запрещенное слово в элементе, приведенном к нижнему регистру..
            raise NoDogsAllowedException('Никаких собак!') # ..вызывается исключение NoDogsAllowedException

    print('Можете проходить..') # если слово не найдено, выводится это сообщение

if __name__ == '__main__':
    group1 = ('Кот', 'Черепаха', 'Попугай')
    group2 = ('Собака в шляпе', 'Кот', 'Мышь')

    try: # проверка первого списка
        checking(*group1)
    except NoDogsAllowedException as e:
        print(e)

    try: # проверка второго списка
        checking(*group2)
    except NoDogsAllowedException as e:
        print(e)
```

1. Блоки try-except нужны, чтобы обработать исключения с учетом разных сценарев (без необходимости завершения уже работающей программы).
2. Создание собственных исключений позволяет более точно определить и обработать специфические ошибочные ситуации.
